### ISSUE TITLE
Header style mutates font attribute on iOS

### ISSUE THREAD

**Issue by mikepulaski** [mattt/CommonMarkAttributedString#1]
On iOS, using any header style will cause the font to mutate to a different family (Times New Roman). I believe this is due to how the font is transformed in the `Header` extension defined in `CommonMark+Extensions.swift`. It's not clear whether or not this happens when the font's point size is made larger, or when the bold trait is added.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/47162/78134083-d8e64800-741f-11ea-8ba9-e248bc3f15b5.png">

For reference, I'm using `UIFont.systemFont(ofSize:)`. It also seemed to be an issue when using `UIFont.preferredFont(forTextStyle: .body)`.

I'm happy to dive in and create a PR for this -- seems like it could be an easy fix!

**Comment by mattt** [comment]
Hey, @mikepulaski. Thanks for reporting this. Yeah, if you have some time to spare, I'd really appreciate a fix for this. I think your diagnosis is spot on — macOS support was my motivating use case, and the code dealing with `UIFontDescriptor` was written in a bit of a hurry.

**Comment by mikepulaski** [comment]
@mattt All set! I added a test (although I don't think running `swift test` actually imports UIKit. See #2.

Looks good, though:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/47162/78200808-09fe6100-7490-11ea-993a-a6f7ca6a96f1.png">

**Comment by mattt** [comment]
Great work, @mikepulaski! Thanks again for taking a crack at that.
 
> (I don't think running `swift test` actually imports UIKit)

Correct. To run these tests on CI, we [generate an Xcode project and run the test bundle with `xcodebuild`](https://github.com/mattt/CommonMarkAttributedString/blob/c5a64a409024078fd1768a6bca6c2e00c5be76c9/.github/workflows/ci.yml#L19-L22).
